### ISSUE TITLE
Manual adjustments of Bayesian prior within correlation-function?

### ISSUE THREAD

**Issue by LuRoe7** [easystats/correlation#102]
Concerning Bayesian correlations on partialized data:

Is it possible to adjust the prior manually within the correlation function instead of using a Cauchy distribution with location = 0 and the different options for the scale parameter r (medium.narrow, medium etc.)?

In particular, I´m interested in changing the location of the prior to approx. 0.2 and/or to set an restriction on the prior distribution at 0?

Thanks!

**Comment by DominiqueMakowski** [comment]
I don't think so... Essentially, for now, our Bayesian correlations rely on the function for correlation tests implemented in the BayesFactor package. I don't know if that's possible in BayesFactor to manually set the prior to some custom value. That said, If you want tighter control over priors specifications, I'd suggest moving directly to brms/rstanarm and fitting GLMs ☺️
