### ISSUE TITLE
Where is this link??

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#103]
CRAN checks say:

```
Found the following (possibly) invalid URLs:
  URL: http://www.jstatsoft.org/v46/i11/ (moved to https://www.jstatsoft.org/v46/i11/)
    From: inst/doc/types.html
    Status: 200
```

But I cannot find where is this link am I blind?

**Comment by strengejacke** [comment]
https instead http

**Comment by DominiqueMakowski** [comment]
Yes, but I don't find where to replace it

**Comment by strengejacke** [comment]
https://github.com/easystats/correlation/search?q=jstatsoft&type=

**Comment by DominiqueMakowski** [comment]
I got misled by the `inst/doc/types.html` I thought it was in the "types.Rmd" vignette. Thanks for showing my the power of GH's search ^^

**Comment by DominiqueMakowski** [comment]
(I mean it sort of was in it but didn't think of looking in the bib)
