### ISSUE TITLE
Biserial correlation

### ISSUE THREAD

**Issue by caiyuqing** [easystats/correlation#105]
Dear Dominick,

Thank you very much for this wonderful package. However, I encountered a problem doing biserial correlation and I am wondering if you could help me take a look at it. 

I am doing a biserial correlation on two SES score and the result (see picture attached) shows that the coefficient is greater than 1.
![image](https://user-images.githubusercontent.com/37493324/93963341-81ea7b80-fd8f-11ea-83aa-3fbf70c57163.png)

I guess it happens because the proportions of the two categories are very different:
![image](https://user-images.githubusercontent.com/37493324/93964261-caa33400-fd91-11ea-8277-de76c5110e82.png)

I also tried to calculate the result manually by transforming the point-biserial coefficient to biserial coefficient and the result is also greater than 1 but it is different from the one calculated from the package:

_The equation:_
![image](https://user-images.githubusercontent.com/37493324/93964738-fecb2480-fd92-11ea-91de-bc0875e2508f.png)
_The result calculated by equation_
![image](https://user-images.githubusercontent.com/37493324/93964369-fd4d2c80-fd91-11ea-9539-41ab2cca9518.png)

What should I do to calculate the biserial correlation under this circumstance? Could you give me some suggestions regarding this issue? 

Thank you very much!
Best wishes,
Yuqing

**Comment by DominiqueMakowski** [comment]
Mmh curious. Would you have a reproducible example so that I can see what's going on? Thanks

**Comment by caiyuqing** [comment]
Thank you very much for replying! Here are the data and code that I used. 
I only selected two variables c1 and e1, which are two SES indexes.

[biserial data and code.zip](https://github.com/easystats/correlation/files/5266195/biserial.data.and.code.zip)

**Comment by DominiqueMakowski** [comment]
I managed to reproduce, and your data seems in order. 

I think the "issue" (not sure whether is an issue) might lie in the formula. The one used currently in correlation (see here)[https://github.com/easystats/correlation/blob/master/R/cor_test_biserial.R#L48] was taken from the psych package (https://github.com/cran/psych/blob/master/R/tetrachor.R#L376) that is usually quite trustworthy. However, when I try to use directly the `psych::biserial()` function from the psych package on your data, it fails 😕 I'm not sure why...

What do you think about the current formula?

**Comment by caiyuqing** [comment]
Hi Dominique, I looked at the link you send me. Although I am not very good at codes, I think the formula is the same as I read somewhere else (this link: https://www.statisticshowto.com/point-biserial-correlation/ and also a book called<Discovering Statistics with R>). I cannot see anything wrong with the formula.
In addition, I also tried the polyserial function from package "polycor". It has an option to choose either "maximum-likelihood estimate" or "two-step approximation". For other variables in my data, the result of "maximum-likelihood" option is the same as the formula. But it won't give me any result for those two variables (c1 and e1). If I choose "two-step approximation", it gives me the same result as ``psych::biserial``(0.999).... I am really confused at this result...

Do you think it is reasonable to just use point-biserial correlation (although the binary variable "e1" does have a ranking between 0 and 1)?

Many thanks for taking time at my question.

**Comment by DominiqueMakowski** [comment]
Yes I think you can go ahead using a point-biserial correlation (`method="pointbiserial"` and not `method="biserial"`), because of its straightforward implementation and interpretation. I don't see any strong statistical reasons why this would be problematic ☺️
