### ISSUE TITLE
Add 'alternative' argument to cor_test() documentation

### ISSUE THREAD

**Issue by baranovskypd** [easystats/correlation#106]
Hi, some time ago I made a feature suggestion to add directional hypothesis testing to `cor_test()` with the `alternative` argument that takes values `'greater'`, `'less'`, or `'two.sided'`. Thank you again for doing this. 

I see that directional testing now works in the CRAN version too. However, neither CRAN pdf nor `?cor_test` show the new argument. Could you please add it to the `cor_test()` documentation?

**Comment by DominiqueMakowski** [comment]
oops, seems like I missed this. Will put it on my list!

**Comment by IndrajeetPatil** [comment]
Hmm, the reason this argument is not documented is because `alternative` argument is actually passed to the relevant method via `...`. 

``` r
library(correlation)

cor_test(iris, "Sepal.Length", "Sepal.Width")
#> Parameter1   |  Parameter2 |     r |        95% CI | t(148) |     p |  Method | n_Obs
#> -------------------------------------------------------------------------------------
#> Sepal.Length | Sepal.Width | -0.12 | [-0.27, 0.04] |  -1.44 | 0.152 | Pearson |   150

cor_test(iris, "Sepal.Length", "Sepal.Width", alternative = 'greater')
#> Parameter1   |  Parameter2 |     r |        95% CI | t(148) |     p |  Method | n_Obs
#> -------------------------------------------------------------------------------------
#> Sepal.Length | Sepal.Width | -0.12 | [-0.25, 1.00] |  -1.44 | 0.924 | Pearson |   150
```

We will either have to explicitly add a new argument called `alternative` and pass it to the method, or inherit documentation for the respective method by using `#' @inheriDotParams`. I think the former is the easiest solution.

**Comment by strengejacke** [comment]
Or just make it more explicit:

> ... Arguments passed to or from other methods.

Could be "further arguments passed down to xyz, see ?xyz for details."
