### ISSUE TITLE
Error in calling correlation with multilevel parameter

### ISSUE THREAD

**Issue by Kuroshiwo** [easystats/correlation#112]
> correlation(data, multilevel = TRUE)
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

**Comment by DominiqueMakowski** [comment]
Hi @Kuroshiwo, I know someone that recently experienced a similar issue, which got solved by updating easystats from github. Could you try running:

```r
remotes::install_github("easystats/insight")
remotes::install_github("easystats/parameters")
remotes::install_github("easystats/correlation")
```

And then trying again?

**Comment by Kuroshiwo** [comment]
Thanks, I will try it and provide a feedback.

**Comment by Kuroshiwo** [comment]
Thank you Dominique. The remote installation worked.

I will close the issue.
