### ISSUE TITLE
improving `Method` column details

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#113]
Current details reported in `Method` are rather unsatisfactory (compare the output from `parameters`):

``` r
library(parameters)
library(magrittr)

cor.test(iris$Sepal.Length, iris$Sepal.Width) %>% 
  parameters() %>% 
  as.data.frame()
#>          Parameter1       Parameter2          r         t df_error         p
#> 1 iris$Sepal.Length iris$Sepal.Width -0.1175698 -1.440287      148 0.1518983
#>       CI_low    CI_high                               Method
#> 1 -0.2726932 0.04351158 Pearson's product-moment correlation

library(correlation)

correlation(dplyr::select(iris, Sepal.Length, Sepal.Width)) %>% 
  as.data.frame()
#>     Parameter1  Parameter2          r     CI_low    CI_high         t  df
#> 1 Sepal.Length Sepal.Width -0.1175698 -0.2726932 0.04351158 -1.440287 148
#>           p  Method n_Obs
#> 1 0.1518983 Pearson   150
```

<sup>Created on 2021-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by DominiqueMakowski** [comment]
Pearson's product-moment correlation?

![](https://media.giphy.com/media/2d98nRiVVB6HS/giphy.gif)

**Comment by DominiqueMakowski** [comment]
but yeah, we should standardize that, what's are the optimal "Method" output for spearman, kendall and pearson?

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil what would be the best content in your opinion for the different methods?

**Comment by IndrajeetPatil** [comment]
Oops, sorry, missed this. 

I think, for internal consistency, we can use the same details as here:

https://github.com/easystats/correlation/blob/9c2379a5fa4e529024d67d2d384b0fc34fd67a32/R/correlation.R#L14-L29

So, for example, `Method` column will change from `Spearman` to `Spearman's rank correlation`.
Does that sound reasonable?

**Comment by IndrajeetPatil** [comment]
Still not fixed, so keeping it open until I work on that PR.
