### ISSUE TITLE
`df` column should be renamed to `df_error`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#118]
To be internally consistent in the `easystats` ecosystem:

``` r
x <- c(44.4, 45.9, 41.9, 53.3, 44.7, 44.1, 50.7, 45.2, 60.1)
y <- c( 2.6,  3.1,  2.5,  5.0,  3.6,  4.0,  5.2,  2.8,  3.8)
df <- data.frame(x = x, y = y)
  
as.data.frame(parameters::model_parameters(cor.test(x, y)))
#>   Parameter1 Parameter2         r        t df_error         p     CI_low
#> 1          x          y 0.5711816 1.841083        7 0.1081731 -0.1497426
#>     CI_high                               Method
#> 1 0.8955795 Pearson's product-moment correlation

as.data.frame(correlation::correlation(df))
#>   Parameter1 Parameter2         r     CI_low   CI_high        t df         p
#> 1          x          y 0.5711816 -0.1497426 0.8955795 1.841083  7 0.1081731
#>    Method n_Obs
#> 1 Pearson     9
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
@strengejacke, @DominiqueMakowski Do you agree? If yes, I will work on a PR.

**Comment by strengejacke** [comment]
I'd ask @mattansb because I'm not sure if there are error-dfs (though it would be in line with effectsizes from `model_parameters()`?).

**Comment by mattansb** [comment]
Yup, that should be `df_error` as well.

**Comment by IndrajeetPatil** [comment]
Cool. 

I have already made a PR here to switch to `df_error`: https://github.com/easystats/correlation/pull/120/files

Also, I am not sure if the difference in order of columns across packages is intentional? 
Should we be consistent on that front as well?

**Comment by DominiqueMakowski** [comment]
Thanks @IndrajeetPatil for updating! I think the order should be consistent as well :)

**Comment by IndrajeetPatil** [comment]
The order should actually be changed in `parameters` (not `correlation`), since the CIs are not right after the estimate.
