### ISSUE TITLE
correlation tables with p values?

### ISSUE THREAD

**Issue by gorkang** [easystats/correlation#145]
Is there a way to have the actual p values instead of *'s in the correlation tables? 

Right now the output is this:  
``` r
library(dplyr)
library(correlation)

# Correlaton table
iris %>% 
  correlation(partial = TRUE) %>% 
  summary() %>% parameters::print_md()
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Petal.Width</th>
<th style="text-align: center;">Petal.Length</th>
<th style="text-align: center;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">-0.34***</td>
<td style="text-align: center;">0.72***</td>
<td style="text-align: center;">0.63***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">0.35***</td>
<td style="text-align: center;">-0.62***</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">0.87***</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

> Correlation Matrix (pearson-method)
> p-value adjustment method: Holm (1979)
> 

But I would love to show something like this... ideally with a nice simple parameter :)  

``` r
# Desired output (instead of *** we have p values). This is a very hacky way to make it similar to the table above.
iris %>% 
  correlation(partial = TRUE) %>% 
  mutate(result = paste0(round(r, 3), " (", gsub("p < ", "<", insight::format_p(p)), ")")) %>% 
  select(Parameter1, Parameter2, result) %>% 
  tidyr::pivot_wider(names_from = Parameter2, values_from = result) %>% 
  select(Parameter1, Petal.Width, Petal.Length, Sepal.Width ) %>% 
  mutate_if(is.character, ~replace(., is.na(.), "")) %>% 
  knitr::kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: left;">Petal.Width</th>
<th style="text-align: left;">Petal.Length</th>
<th style="text-align: left;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: left;">-0.34 (&lt;.001)</td>
<td style="text-align: left;">0.719 (&lt;.001)</td>
<td style="text-align: left;">0.629 (&lt;.001)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: left;">0.353 (&lt;.001)</td>
<td style="text-align: left;">-0.615 (&lt;.001)</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: left;">0.871 (&lt;.001)</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>

<sup>Created on 2021-03-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
@IndrajeetPatil @DominiqueMakowski I think this is something that is done inside the _correlation_ pkg and its summary() and print() methods.

**Comment by DominiqueMakowski** [comment]
This should work now:

``` r
summary(correlation::correlation(iris),
        stars = FALSE, include_significance = TRUE)
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter    |      Petal.Width |     Petal.Length |       Sepal.Width
#> ----------------------------------------------------------------------
#> Sepal.Length |  0.82 (p < .001) |  0.87 (p < .001) | -0.12 (p = 0.152)
#> Sepal.Width  | -0.37 (p < .001) | -0.43 (p < .001) |                  
#> Petal.Length |  0.96 (p < .001) |                  |                  
#> 
#> p-value adjustment method: Holm (1979)
```

<sup>Created on 2021-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gorkang** [comment]
This is fantastic! Thanks @DominiqueMakowski !

Just for future reference. With this correlation tables it is quite easy to adapt to the format of your choice (a couple examples below).  

One small thing (feel free to ignore) is that I can't control the number of digits of the p value (see below).

``` r
library(dplyr)
library(correlation)

table_corr = 
  summary(correlation::correlation(iris),
          stars = FALSE, include_significance = TRUE) %>%
  parameters::print_md()

gsub(" \\(p = | \\(p ", " \\(", table_corr, ignore.case = FALSE)
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Petal.Width</th>
<th style="text-align: center;">Petal.Length</th>
<th style="text-align: center;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">0.82 (&lt; .001)</td>
<td style="text-align: center;">0.87 (&lt; .001)</td>
<td style="text-align: center;">-0.12 (0.152)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">-0.37 (&lt; .001)</td>
<td style="text-align: center;">-0.43 (&lt; .001)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">0.96 (&lt; .001)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

``` r
gsub(" \\(p ", "<BR>(p ", table_corr, ignore.case = FALSE)
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Petal.Width</th>
<th style="text-align: center;">Petal.Length</th>
<th style="text-align: center;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">0.82<BR>(p &lt; .001)</td>
<td style="text-align: center;">0.87<BR>(p &lt; .001)</td>
<td style="text-align: center;">-0.12<BR>(p = 0.152)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">-0.37<BR>(p &lt; .001)</td>
<td style="text-align: center;">-0.43<BR>(p &lt; .001)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">0.96<BR>(p &lt; .001)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>


### Can't control the number of digits of the p value

A small issue is that I can seem to be able to pass the `digits` parameter to control the number of digits of the p value, as in ´insight::format_p(digits = 5)´.

``` r
summary(correlation::correlation(iris, ),
        stars = FALSE, 
        include_significance = TRUE, 
        digits = 5) %>%  # NOT working
  parameters::print_md()
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Petal.Width</th>
<th style="text-align: center;">Petal.Length</th>
<th style="text-align: center;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">0.82 (p &lt; .001)</td>
<td style="text-align: center;">0.87 (p &lt; .001)</td>
<td style="text-align: center;">-0.12 (p = 0.152)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">-0.37 (p &lt; .001)</td>
<td style="text-align: center;">-0.43 (p &lt; .001)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">0.96 (p &lt; .001)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>


<sup>Created on 2021-03-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
thanks for the feedback, this should now work:


``` r
summary(correlation::correlation(iris),
        stars = F, include_significance = TRUE, p_digits = 4)
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter    |            Petal.Width |           Petal.Length |        Sepal.Width
#> -----------------------------------------------------------------------------------
#> Sepal.Length |  0.82 (p = 9.3020e-37) |  0.87 (p = 5.1933e-47) | -0.12 (p = 0.1519)
#> Sepal.Width  | -0.37 (p = 8.1465e-06) | -0.43 (p = 1.3540e-07) |                   
#> Petal.Length |  0.96 (p = 2.8050e-85) |                        |                   
#> 
#> p-value adjustment method: Holm (1979)
```

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gorkang** [comment]
Wow, thanks again @DominiqueMakowski !

It seems that now, the `stars` parameter does not reach `parameters::print_md()`? As you can see below, the stars always appear, regardless of the `stars` parameter value.

``` r
library('correlation')
library(dplyr)

summary(correlation::correlation(iris),
        stars = F, include_significance = TRUE)
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter    |      Petal.Width |     Petal.Length |       Sepal.Width
#> ----------------------------------------------------------------------
#> Sepal.Length |  0.82 (p < .001) |  0.87 (p < .001) | -0.12 (p = 0.152)
#> Sepal.Width  | -0.37 (p < .001) | -0.43 (p < .001) |                  
#> Petal.Length |  0.96 (p < .001) |                  |                  
#> 
#> p-value adjustment method: Holm (1979)

summary(correlation::correlation(iris),
        stars = F, include_significance = TRUE) %>% 
  parameters::print_md()
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Petal.Width</th>
<th style="text-align: center;">Petal.Length</th>
<th style="text-align: center;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">0.82 (p &lt; .001***)</td>
<td style="text-align: center;">0.87 (p &lt; .001***)</td>
<td style="text-align: center;">-0.12 (p = 0.152)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">-0.37 (p &lt; .001***)</td>
<td style="text-align: center;">-0.43 (p &lt; .001***)</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">0.96 (p &lt; .001***)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

Correlation Matrix (pearson-method)

p-value adjustment method: Holm (1979)

<sup>Created on 2021-03-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
Thanks @gorkang, I r the vamped the printing in the latest, could you test it out and let me know if everything works 😁

**Comment by gorkang** [comment]
@DominiqueMakowski , everything works beautifully. Thanks again for your awesomeness :1st_place_medal:
