### ISSUE TITLE
adjust/partialize by selected column

### ISSUE THREAD

**Issue by mattansb** [easystats/correlation#147]
Currently I can only partialize by all the "other" selected columns (the ones that aren't part of the correlation).

It would be nice to be able to "fix" which columns I want to partialize by. 

For example, I can get multi-level correlations this way:

```r
correlation::correlation(
  iris,
  partial_by = "Species", # <<<<<<<<<<<<
  partial = TRUE,
  multilevel = TRUE
)
```

**Comment by DominiqueMakowski** [comment]
rather than adding a new arg `partial_by` I'd just allow `partial` to take in characters vectors:

```r
correlation::correlation(iris, partial = "Species", multilevel = TRUE)
```

**Comment by jmgirard** [comment]
This was closed but didn't seem to have been implemented.

**Comment by mattansb** [comment]
Closing in favor of #311
