### ISSUE TITLE
robust correlations with 'ranktransform' 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#15]
as shown by @lindeloev, Spearman correlations can be estimated using a rank transformation. Hence, it might be interesting to develop a more flexible framework for robust spearman-like correlations now that we have `ranktransform()` in effectsize, to make it work with all the correlation types, Bayesian, partial etc.

**Comment by IndrajeetPatil** [comment]
This is another option for implementing a robust correlation coefficient:
https://rdrr.io/cran/WRS2/man/pbcor.html

Code:
https://github.com/cran/WRS2/blob/master/R/pbcor.R

This paper presents some evidence for why percentage bend is more robust than Spearman:
https://www.frontiersin.org/articles/10.3389/fpsyg.2012.00606/full

**Comment by DominiqueMakowski** [comment]
Also, this paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3397314/ showing the Shepherd's pi correlation. Can add both percent bend and shepherd's pi
