### ISSUE TITLE
feature request: add df's to cor_test

### ISSUE THREAD

**Issue by fuhred** [easystats/correlation#166]
would be great to see a colum for df's in cor_test

**Comment by IndrajeetPatil** [comment]
When available, the degrees of freedom are already reported in the `df_error` column:

``` r
library(correlation)

as.data.frame(cor_test(iris, "Sepal.Length", "Sepal.Width"))
#>     Parameter1  Parameter2          r   CI     CI_low    CI_high         t
#> 1 Sepal.Length Sepal.Width -0.1175698 0.95 -0.2726932 0.04351158 -1.440287
#>   df_error         p  Method n_Obs
#> 1      148 0.1518983 Pearson   150
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Just for the record, if the df do _not_ vary by parameters, these are printed in parenthesis in the statistic-column:

``` r
library(correlation)
cor_test(iris, "Sepal.Length", "Sepal.Width")
#> Parameter1   |  Parameter2 |     r |        95% CI | t(148) |     p
#> -------------------------------------------------------------------
#> Sepal.Length | Sepal.Width | -0.12 | [-0.27, 0.04] |  -1.44 | 0.152
#> 
#> Observations: 150
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by fuhred** [comment]
I am so sorry. This is very embarassing--I was using rstatix::cor_test.

**Comment by IndrajeetPatil** [comment]
Oh? Good to know about this namespace collision.
