### ISSUE TITLE
Nonstandard evaluation (selection helpers ala subset, tidyselect, mosaic?)

### ISSUE THREAD

**Issue by bwiernik** [easystats/correlation#179]
Many users are likely to come to *correlation* through either tidyverse or even base R `subset()`. Doing some initial teaching with *correlation* recently, I saw some friction with the `select` and `select2` arguments only accepting character vectors and not nonstandard evaluation or related helpers. 

For example, this is acceptable code in subset:
```r
subset(mtcars, select = mpg:hp)
```

But not in correlation:
```r
correlation::correlation(mtcars, select = mpg:hp)
```

We can implement support for nonstandard evaluation without dependencies if we implement a method ala `select` in `base::subset()`:

```r
subset.data.frame <- function (x, subset, select, drop = FALSE, ...) 
{
    r <- if (missing(subset)) 
        rep_len(TRUE, nrow(x))
    else {
        e <- substitute(subset)
        r <- eval(e, x, parent.frame())
        if (!is.logical(r)) 
            stop("'subset' must be logical")
        r & !is.na(r)
    }
    vars <- if (missing(select)) 
        rep_len(TRUE, ncol(x))
    else {
        nl <- as.list(seq_along(x))
        names(nl) <- names(x)
        eval(substitute(select), nl, parent.frame())
    }
    x[r, vars, drop = drop]
}
```

This would enable selection using unquoted names, name ranges, and numeric vectors. With slight adaptation to the style used by *dplyr*, it would also permit dplyr users to use functions like `starts_with()`:
```r
library(dplyr)
library(correlation)

correlation(iris, select = c(Sepal.Length, Sepal.Width))
correlation(iris, select = Sepal.Length:Sepal.Width)

correlation(iris, select = c(1, 2))
correlation(iris, select = starts_with("Sepal", vars = names(iris))
```

### Additional options

1. `subset`
We could similarly add a subset argument taking a logical vector ala the same argument in `subset()` or `lm()`. I personally wouldn't use this much, but I know a lot of folks that like to use the `subset` argument. 

2. `formula`
We could also consider supporting a formula interface ala *mosaic*. This would be similar the formula interfaces provided by modeling functions like `lm()` or `brm()` (and indeed `brm()`'s multivariate interface [could be used to compute Bayesian correlations somewhat inefficiently](https://solomonkurz.netlify.app/post/2019-02-16-bayesian-correlations-let-s-talk-options/)). I'm less enthusiastic about this, and I would only want to do this as part of a separate `formula` argument rather than trying to double-dip on `select`.

**Comment by bwiernik** [comment]
The above recommendations wouldn't give all of the tidyselect bells and whistles, but it would give the most common ones without any dependencies.

**Comment by DominiqueMakowski** [comment]
that'd be great indeed! I think we have several instances throughout easystats where we have a `select` or functionally similar argument.

Maybe we could add in `insight` a function called `data_select()` that would be quite flexible (working with strings and the NSE specifications that you mentioned) and use it here?

**Comment by mattansb** [comment]
Closing in favor of #232
