### ISSUE TITLE
Other correlations types

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#2]
- Frequentist
  - [x] Partial
  - [x] Robust (spearman)
  - [x] Tetrachoric, polychoric etc.: For ordinal, binary, etc. data
- Bayesian
  - [x] Partial
  - [ ] Robust
  - [ ] Tetrachoric, polychoric

## Inspiration
- psych: [polychoric](https://github.com/cran/psych/blob/master/R/polychoric.R), [tetrachoric](https://github.com/cran/psych/blob/master/R/tetrachor.R)
- lavaan: [lavCor](https://github.com/yrosseel/lavaan/blob/master/R/lav_cor.R)
- [Bayesian polychoric correlation](https://open.library.ubc.ca/media/download/pdf/24/1.0073832/1)
- https://jimgrange.wordpress.com/2017/11/19/bayesian-estimation-of-partial-correlations/
- https://cran.r-project.org/web/packages/BayesMed/BayesMed.pdf

**Comment by DominiqueMakowski** [comment]
[Bayesian polychoric correlation](https://open.library.ubc.ca/media/download/pdf/24/1.0073832/1)

**Comment by JauntyJJS** [comment]
Hi,

In genomics, we usually use the biweight correlation from the WCGNA package
More details can be found in

https://en.wikipedia.org/wiki/Biweight_midcorrelation
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3465711/

I understand this is outside your field but adding this feature and making it tidy is something that 
no one has done before in my knowledge...

Perhaps it could be something to look into to push the package towards a larger group of users.

**Comment by DominiqueMakowski** [comment]
@JauntyJJS very interesting, I didn't even know this method existed! From the description, I guess it could be used beyond genomics... 

I'll definitely look at the possibility of adding that, I'll keep you updated!

**Comment by DominiqueMakowski** [comment]
this issue has been outsourced to #16 and #15
