### ISSUE TITLE
correlation

### ISSUE THREAD

**Issue by BB1464** [easystats/correlation#220]
Good Morning Dear All,
       Please I am trying to use your package to run correlation and I have 25 variables but when the output comes out in R markdown they are all overlapping on each other but when I pass the output to flextable it drops the significant output in which I need this significant asterisks to include in my report, is there any function to pass to flextable that will display the significant asterisk ? find below my codes:

res<-correlation(data2)
summary(res) %>% flextable::flextable()

**Comment by bwiernik** [comment]
I don't know how correlation interactions with flextable 

You might try to let easystats convert it to a markdown table for you:

```r
correlation::correlation(dat) |>
  summary() |>
  insight::print_md()
```

**Comment by BB1464** [comment]
Thank you very much for your response, this is very helpful, but I have to
use the magritr pipe and I got my results. Cheers.
