### ISSUE TITLE
changed multilevel correlations

### ISSUE THREAD

**Issue by BobbWANG** [easystats/correlation#222]
We have collected multilevel data recently, where each participant rates two organizations, and each organization has multiple raters. One of our research purposes is to acquire validation correlations between Q-sort component scores and Likert scale items. Therefore we have to calculate multilevel correlations by using the correlation R package, participants and organizations are considered as factors. However, when using this package, I found that the correlations would change slightly depending on which variables are included. For example, the correlation between A and B, when the variable set consists of variables A, B, C, D, is different from the correlation between A and B,  when the variable set consists of variables A, B, E, F. After checking the package manual, I guess it is because the correlation function does 'a back-transformation from partial to non-partial correlation and this process will lead to some deviation as the original partial multilevel correlations depend on the variable set. But I'm not sure whether my inference is correct. 

I have two other questions :
1. What is the rationale underlying the correlation package to acquire multilevel correlations? Would you like to give some references?
2. Is there any other method to acquire multilevel correlations without estimating partial correlations?

Really appreciate any suggestions and help!

**Comment by bwiernik** [comment]
You might prefer to use the `statsBy` function in the *psych* package:

``` r
library(psych)
dat <- bfi |> 
  na.omit() |> 
  transform(group = paste(gender, education, sep = "_")) |> 
  subset(select = c(paste0("A", 1:5), "group"))
stats <- statsBy(dat, "group")
print(stats, short = FALSE)
#> Statistics within and between groups  
#> Call: statsBy(data = dat, group = "group")
#> Intraclass Correlation 1 (Percentage of variance due to groups) 
#>    A1    A2    A3    A4    A5 group 
#>  0.05  0.05  0.03  0.04  0.01  1.00 
#> Intraclass Correlation 2 (Reliability of group differences) 
#>    A1    A2    A3    A4    A5 group 
#>  0.93  0.93  0.88  0.91  0.72  1.00 
#> eta^2 between groups  
#> A1.bg A2.bg A3.bg A4.bg A5.bg 
#>  0.05  0.05  0.03  0.04  0.01 
#> Correlation between groups 
#>       A1.bg A2.bg A3.bg A4.bg A5.bg
#> A1.bg  1.00                        
#> A2.bg -0.74  1.00                  
#> A3.bg -0.60  0.95  1.00            
#> A4.bg -0.28  0.76  0.84  1.00      
#> A5.bg -0.68  0.82  0.85  0.61  1.00
#> Correlation within groups 
#>       A1.wg A2.wg A3.wg A4.wg A5.wg
#> A1.wg  1.00                        
#> A2.wg -0.32  1.00                  
#> A3.wg -0.25  0.47  1.00            
#> A4.wg -0.14  0.32  0.36  1.00      
#> A5.wg -0.17  0.37  0.50  0.31  1.00
#> 
#> Many results are not shown directly. To see specific objects select from the following list:
#>  mean sd n F ICC1 ICC2 ci1 ci2 raw rbg ci.bg pbg rwg nw ci.wg pwg etabg etawg nwg nG Call
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
