### ISSUE TITLE
Controlling for type of correlation plot

### ISSUE THREAD

**Issue by harshvardhaniimi** [easystats/correlation#223]
I tried following the example posted on your [vignette](https://easystats.github.io/see/articles/correlation.html).

```
corr = correlation(mod2, select = c("Alpha_o.x", "Beta_o.x", "Gamma_o.x", 
                                    "Alpha_o.y", "Beta_o.y", "Gamma_o.y"))

summary(corr) %>%
  plot()
```

This generates a plot like the following.
![image](https://user-images.githubusercontent.com/40472851/144294518-f3eace5b-2a5a-4e17-90e9-0b182ff1f766.png)

However, I was expecting a block correlation plot like your example, which follows the same code.
<img width="675" alt="Screen Shot 2021-12-01 at 1 44 32 PM" src="https://user-images.githubusercontent.com/40472851/144294669-9ee302ac-26b9-45f5-bad9-e0d355e16352.png">

What is the default option for generating the plot, and how is that different between the machines? Is there a way to control the type of plot generated?

**Comment by bwiernik** [comment]
Update to the latest version of *correlation*, which defaults to tiles.

`install.packages("correlation", repos = "https://easystats.r-universe.dev/")`

You can switch between the formats with the `show_data` argument.

`summary(corr) |> plot(show_data = "tile") # default`
`summary(corr) |> plot(show_data = "point") # circles`
