### ISSUE TITLE
Is there a way to specify fixed and random effects separately?

### ISSUE THREAD

**Issue by andreifoldes** [easystats/correlation#226]
Greetings,

I have a multilevel dataset where I have a _subject_ level data group by experimental _condition_, so I would like to include "subject" as a random effect and have condition as a "fixed" effect - would this be possible in this package?

**Comment by DominiqueMakowski** [comment]
Hi, not really, for that, best to fit directly the mixed model you want. You can then attempt to convert your estimates in partial correlations using https://easystats.github.io/effectsize/articles/convert.html
