### ISSUE TITLE
CRAN submission 0.8.0

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#229]
@bwiernik (cc @strengejacke) Everything checks out for CRAN submission!

So up to you when you want to submit the update to CRAN.

**Comment by IndrajeetPatil** [comment]
I think we need to fix #214 and #215 before submission.

**Comment by bwiernik** [comment]
Okay, figured out what's happening. Conflicts between the structure of the old and new APIs. We need to decide how to resolve those.

**Comment by IndrajeetPatil** [comment]
I think now we are ready for submission.

**Comment by strengejacke** [comment]
What's the state of submission? I think we need _correlation_ on CRAN before _see_.
