### ISSUE TITLE
Citations for distance correlations appear to be missing?

### ISSUE THREAD

**Issue by TarandeepKang** [easystats/correlation#234]
Dear team, I think I've spotted some missing citations for the distance correlations. 

https://easystats.github.io/correlation/articles/types.html

I assume that you are using a similar implementation to that within the "energy" package?

According to the package authors the relevant citations are:

Szekely, G.J., Rizzo, M.L., and Bakirov, N.K. (2007), Measuring and Testing Dependence by Correlation of Distances, Annals of Statistics, Vol. 35 No. 6, pp. 2769-2794.
doi: [10.1214/009053607000000505](https://doi.org/10.1214/009053607000000505)

Szekely, G.J. and Rizzo, M.L. (2009), Brownian Distance Covariance, Annals of Applied Statistics, Vol. 3, No. 4, 1236-1265.
doi: [10.1214/09-AOAS312](https://doi.org/10.1214/09-AOAS312)

Szekely, G.J. and Rizzo, M.L. (2009), Rejoinder: Brownian Distance Covariance, Annals of Applied Statistics, Vol. 3, No. 4, 1303-1308.

**Comment by DominiqueMakowski** [comment]
thanks! would you like to make a PR to add the relevant citations where appropriate?
