### ISSUE TITLE
Getting rid of a warning in `correlation()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#235]
> Warning: No column names that matched the required search pattern were found.

Reprex:

``` r
library(correlation)
correlation(BOD, standardize_names = TRUE)
#> Warning: No column names that matched the required search pattern were found.
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter1 | Parameter2 |    r |        95% CI | t(4) |     p
#> -------------------------------------------------------------
#> Time       |     demand | 0.80 | [-0.02, 0.98] | 2.70 | 0.054
#> 
#> p-value adjustment method: Holm (1979)
#> Observations: 6
```

<sup>Created on 2022-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
@strengejacke Any ideas? I thought `data_find()` is a drop-in replacement for `data_findcols()`, so a bit surprised by these new warnings.

**Comment by strengejacke** [comment]
We increased verbosity, so just setting verbose to FALSE should work.

**Comment by strengejacke** [comment]
I think we should also set the `regex` argument to `TRUE`, because we use a regular expression here
