### ISSUE TITLE
Question about multilevel correlation

### ISSUE THREAD

**Issue by AnjaSchmutz** [easystats/correlation#237]
Hi there!

I have a question about the method in multilevel correlations. You write that you include the grouping factor as random effect in a mixed effect model. Is this then a random slope model? Or just a random intercept model?

Kind regards,

Anja

**Comment by AnjaSchmutz** [comment]
Hi again :-)

A follow-up question came just up. Is there a way to plot the "overall" correlation line and the correlation lines of the grouping factors (similar to trend lines in mixed effect models and the lines from the coefficients)?

**Comment by camilagazolla** [comment]
Hello! Any news on this? Thank you!

**Comment by strengejacke** [comment]
The model is a random intercept model, i.e. the multilevel correlation is adjusted for `(1 | groupfactor)`.

**Comment by DominiqueMakowski** [comment]
See also https://github.com/easystats/datawizard/issues/203
