### ISSUE TITLE
Get rid of `{tidyr}` and `{forcats}` from `Suggests`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#240]
In favor of _datawizard_ and base-R (cf. https://github.com/easystats/easystats/issues/167).

Also check if _gt_ is really needed.

**Comment by strengejacke** [comment]
I think _gt_ is only "needed" in _insight_, unless one of the examples explicitly create HTML tables?

**Comment by IndrajeetPatil** [comment]
@etiennebacher You wanna take a crack at this?
