### ISSUE TITLE
Should not use *** for self-correlations R(x,x)=1

### ISSUE THREAD

**Issue by friendly** [easystats/correlation#250]
I'm not a fan of significance stars, but certainly in text output and plots, you should not use `***` for the self-correlations r(x,x)=1

**Comment by bwiernik** [comment]
Agreed. Should also change coloring of the diagonal to not be solid and dark. 

What do folks think about changing the defaults to omit stars?

**Comment by strengejacke** [comment]
Diagonal could be solid, or maybe grey? Agree on omitting stars.

**Comment by IndrajeetPatil** [comment]
+1 for omitting stars by default.

**Comment by friendly** [comment]
YES to (light) grey.  Try this to see what a difference it makes to perception.

**Comment by strengejacke** [comment]
``` r
library(correlation)
x <- correlation(iris)
s <- summary(x, redundant = TRUE)
plot(s)
```

![](https://i.imgur.com/EqP86f5.png)

<sup>Created on 2022-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
``` r
library(correlation)
x <- correlation(iris)
s <- summary(x, redundant = TRUE)
plot(s)
```

![](https://i.imgur.com/pxYK2Fs.png)

<sup>Created on 2022-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Plot ok like this, or any suggestions for changes?

**Comment by strengejacke** [comment]
Same for print now:

``` r
library(correlation)
x <- correlation(iris)
summary(x, redundant = TRUE)
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter    | Sepal.Length | Sepal.Width | Petal.Length | Petal.Width
#> ----------------------------------------------------------------------
#> Sepal.Length |              |       -0.12 |      0.87*** |     0.82***
#> Sepal.Width  |        -0.12 |             |     -0.43*** |    -0.37***
#> Petal.Length |      0.87*** |    -0.43*** |              |     0.96***
#> Petal.Width  |      0.82*** |    -0.37*** |      0.96*** |            
#> 
#> p-value adjustment method: Holm (1979)
```

<sup>Created on 2022-08-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Looks good. Can you switch the default to not show stars?

**Comment by DominiqueMakowski** [comment]
isn't showing stars a feature that people are looking for? (and thus could help for the visibility of the package, then it' easy to turn them off)

**Comment by bwiernik** [comment]
IIRC correctly, plot.summary() and print.summary() don't have any argument to disable stars. I personally think they should be non-default
