### ISSUE TITLE
Diagnoze build failures for `R < 4.1`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#259]
Some examples seem to fail:

https://github.com/easystats/correlation/runs/8174676238?check_suite_focus=true

**Comment by strengejacke** [comment]
I think these are the most confusing fails, because it seems to work on other systems, and the error - at first glance - looks like being related to simple base R, which either should fail on _all_ R < 4.1, or not at all (but not only on Linux).

Do we have anyone here using Linux?

**Comment by IndrajeetPatil** [comment]
I don't think we are testing R < 4.1 for any other OS than Linux. 

Have you checked locally 9! Windows that these failures are not observed for R < 4.1?

Alternatively, we can also check on other OS for these R versions.

**Comment by strengejacke** [comment]
Ah, I just saw we have oldrel1-3 for Linux, not the other OS. We could temporarily add oldrel-2 for Windows and check if it occurs there, too. If so, might be an issue with forgetting to set `stringsAsFactor = FALSE` or similar.

**Comment by IndrajeetPatil** [comment]
Cool, will do that in the workflows repo.

**Comment by strengejacke** [comment]
I just debugged the `cor_lower()` function and didn't spot something spurious... Let's see if we find out what's going on here, will revisit once we have test results from windows.

**Comment by IndrajeetPatil** [comment]
As can be seen [here](https://github.com/easystats/correlation/actions/runs/2987401279), builds also fail on macOS and Windows. So this is not OS-specific issue.

**Comment by strengejacke** [comment]
Result for R 4.0.5:

![image](https://user-images.githubusercontent.com/26301769/188306470-dafe1ee9-ebe2-47e7-b550-976ccfe9be28.png)


Result for R 4.2.1:

![image](https://user-images.githubusercontent.com/26301769/188306515-7ff7aaf7-546d-44df-8d20-7dcfb8874b64.png)

**Comment by strengejacke** [comment]
Seems like `cor_sort` should preserve the character class for the parameter columns?

**Comment by DominiqueMakowski** [comment]
Do you guys remember which test failed? Sorry I missed this. But yes, I think by default cor_sort() *should*  transform the param columns to factor otherwise it doesnt show the new order when plotting.
We could add a as.character() transformation in the test if need be

**Comment by IndrajeetPatil** [comment]
Outdated.
