### ISSUE TITLE
When plotting only or mostly positive correlations, color scale is wrong

### ISSUE THREAD

**Issue by mattansb** [easystats/correlation#265]
``` r
set.seed(10)
S <- diag(5)
S[lower.tri(S)] <- runif(10)
S[upper.tri(S)] <- t(S)[upper.tri(S)]
```

These should be all blue

``` r
data <- MASS::mvrnorm(100, rep(0, 5), S) |> 
  as.data.frame()

correlation::correlation(data) |> 
  summary() |> plot()
```

![](https://i.imgur.com/KOcr3ez.png)

Here the colors are just wrong

``` r
S[rbind(c(1,2), c(2,1))] <- -0.02

data <- MASS::mvrnorm(100, rep(0, 5), S) |> 
  as.data.frame()

correlation::correlation(data) |> 
  summary() |> plot()
```

![](https://i.imgur.com/zBfDJ94.png)

<sup>Created on 2022-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
Whatchu mean its wrong?

**Comment by mattansb** [comment]
Oh, sorry! For some reason in my brain red = negative and blue = positive.

Oops!

**Comment by bwiernik** [comment]
Guessing he's thinking that blue should be positive and red negative?

**Comment by mattansb** [comment]
![image](https://user-images.githubusercontent.com/35330040/190395930-b12e0df3-6f45-42d9-99a6-cd7c4831482c.png)

@IndrajeetPatil : your color-relate associations are INVALID! 🤖
