### ISSUE TITLE
CRAN check failures

### ISSUE THREAD

**Issue by bwiernik** [easystats/correlation#283]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_correlation.html>.

Please correct before 2023-04-10 to safely retain your package on CRAN.

Best,
-k

**Comment by strengejacke** [comment]
@IndrajeetPatil I think these issues are fixed, right?

**Comment by IndrajeetPatil** [comment]
To my best knowledge, yes.

That said, I wasn't able to fix one of the examples on the older R versions. You might want to have a look at it and see if fixing is necessary for a CRAN release.

**Comment by strengejacke** [comment]
@IndrajeetPatil  can you please update the snapshot tests?
