### ISSUE TITLE
Suggestion of new function: `cormatrix_to_excel()`

### ISSUE THREAD

**Issue by rempsyc** [easystats/correlation#291]
The `correlation` package has a fantastic way to visualize coloured correlation matrices:

``` r
library(correlation)
library(see)

results <- correlation(iris)
results |>
  summary(redundant = TRUE) |>
  plot()
```

![](https://i.imgur.com/Cb9DHCQ.png)

<sup>Created on 2023-07-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This method is perfect for toy datasets like `iris` or `mtcars`, but quickly get out of hand for large matrices, especially with long variable names.

``` r
library(correlation)
library(see)

data <- read.table("https://osf.io/c5b7r/?action=download", sep = "\t", header = TRUE)

results <- correlation(data[1:30])
results |>
  summary(redundant = TRUE) |>
  plot()
```

![](https://i.imgur.com/Fcp17aY.png)

<sup>Created on 2023-07-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I have noticed that some collaborators don't like images like this for matrix (even when you can save it at a large resolution and get a huge image with readable names). In fact, some profs insist that they want the correlation matrix in Excel format so they can freeze the top and left panes and more easily zero in on the relevant correlation by cross-targeting the relevant variables.

So I have made the function [`rempsyc::cormatrix_excel()`](https://rempsyc.remi-theriault.com/reference/cormatrix_excel.html), which relies on `correlation` to do the matrix, and `openxlsx2` (conditional suggested dependency with `insight::check_if_installed()`) to convert it to Excel, with the first row and column frozen, etc. It contains the colour-coded correlation matrix with significance stars, on the first sheet, and the colour-coded _p_ values on the second sheet. One of the benefit is that the exact numeric values are preserved, and only the display shows rounding and the significance stars.

``` r
cormatrix_excel(
  data = infert,
  filename = "cormatrix1",
  select = c(
    "age", "parity", "induced", "case", "spontaneous",
    "stratum", "pooled.stratum"
  )
)
#> # Correlation Matrix (pearson-method)
#> 
#> Parameter      |      age |   parity |  induced |     case | spontaneous |  stratum | pooled.stratum
#> ----------------------------------------------------------------------------------------------------
#> age            |          |     0.08 |    -0.10 | 3.53e-03 |       -0.08 | -0.21*** |        -0.17**
#> parity         |     0.08 |          |  0.45*** | 8.91e-03 |     0.31*** | -0.31*** |           0.12
#> induced        |    -0.10 |  0.45*** |          |     0.02 |    -0.27*** |    -0.10 |          0.16*
#> case           | 3.53e-03 | 8.91e-03 |     0.02 |          |     0.36*** | 3.83e-03 |       4.86e-03
#> spontaneous    |    -0.08 |  0.31*** | -0.27*** |  0.36*** |             |     0.06 |        0.21***
#> stratum        | -0.21*** | -0.31*** |    -0.10 | 3.83e-03 |        0.06 |          |        0.75***
#> pooled.stratum |  -0.17** |     0.12 |    0.16* | 4.86e-03 |     0.21*** |  0.75*** |               
#> 
#> p-value adjustment method: none
#> 
#> 
#>  [Correlation matrix 'cormatrix1.xlsx' has been saved to working directory (or where specified).]

```
![](https://rempsyc.remi-theriault.com/reference/figures/cormatrix.png)
![](https://rempsyc.remi-theriault.com/reference/figures/cormatrix2.png)

I am open to better name suggestions, like `cormatrix_to_excel()` or something else (any ideas?).

---

**Comment by rempsyc** [comment]
What do you think @easystats/core-team ? If you like it I'll submit a PR <sub> (once my fractured shoulder recovers) </sub>

**Comment by bwiernik** [comment]
Looks good to me! Please do!

**Comment by rempsyc** [comment]
PR submitted in #294! :)
