### ISSUE TITLE
Bootstrapped mahalanobis distance

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#30]
In the paper about Shepherd's pi correlation (#15), they say:

> The Mahalanobis distance (in squared units) measures the distance in multivariate space taking into account the covariance structure of the data. Because a few extreme outliers can skew the covariance estimate, Dm is not robust. We therefore bootstrap the Mahalanobis distance by resampling n observations with replacement (i.e., allowing duplicates) and then calculating the Mahalanobis distance for each actual observation from the bivariate mean of the resampled data. The bootstrapped Mahalanobis distance, Ds, for each observation is the mean across the distances from all resamples.

I tried to add a bootstrapped mahalanobis, but something's wrong (the indices are roughly the same for all observations):

Does anyone have an idea? I added the basis of the function (currently on [dev](https://github.com/easystats/correlation/blob/dev/R/mahalanobis.R))

``` r
.distance_mahalanobis <- function(data, indices = 1:nrow(data), ...) {
  dat <- data[indices, ] # allows boot to select sample
  row.names(dat) <- NULL
  stats::mahalanobis(dat, center = colMeans(dat), cov = stats::cov(dat))
}

rez <- boot::boot(data = mtcars, statistic = .distance_mahalanobis, R = 1000, sim="permutation")
bayestestR::point_estimate(as.data.frame(rez$t), centrality="all")
#> # Point Estimates
#> 
#>  Parameter Median Mean MAP
#>         V1    9.5   11 9.0
#>         V2    9.9   11 9.0
#>         V3    9.5   11 9.0
#>         V4    9.5   11 9.0
#>         V5    9.9   11 9.0
#>         V6    9.5   11 9.0
#>         V7    9.9   11 9.0
#>         V8    9.9   11 9.0
#>         V9    9.5   11 9.0
#>        V10    9.5   10 9.0
#>        V11    9.5   11 9.0
#>        V12    9.7   11 9.0
#>        V13    9.9   11 9.0
#>        V14    9.9   11 9.0
#>        V15    9.9   10 9.0
#>        V16    9.5   10 9.0
#>        V17    9.9   11 9.0
#>        V18    9.5   11 9.0
#>        V19    9.9   11 9.0
#>        V20    9.9   11 9.0
#>        V21    9.5   11 9.0
#>        V22    9.5   11 8.9
#>        V23    9.9   11 9.0
#>        V24    9.9   11 8.9
#>        V25    9.9   11 9.0
#>        V26    9.5   11 9.0
#>        V27    9.5   11 9.0
#>        V28    9.5   10 9.0
#>        V29    9.5   11 9.0
#>        V30    9.5   11 9.0
#>        V31    9.5   10 9.0
#>        V32    9.9   11 9.0
```

<sup>Created on 2019-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JauntyJJS** [comment]
Hi,

From the phrase in the paper
"then calculating the Mahalanobis distance for **each actual observation** from the bivariate mean of the resampled data."

Shouldn't **data** (The actual obervation) be used instead of **dat** (the resampled data) as in 
```{r}
stats::mahalanobis(data, center = colMeans(dat), cov = stats::cov(dat))
```
instead of
```{r}
stats::mahalanobis(dat, center = colMeans(dat), cov = stats::cov(dat))
```

**Comment by JauntyJJS** [comment]
Not sure if you are aware. The author's MATLAB code can be found in https://sampendu.net/publications/

![image](https://user-images.githubusercontent.com/9066508/71622188-0e0bb000-2c0f-11ea-88c5-3774accb3eec.png)

Clicking on the hyperlink "Matlab Code" gives this zip file
[Shepherd.zip](https://github.com/easystats/correlation/files/4012705/Shepherd.zip)

**Comment by DominiqueMakowski** [comment]
@JauntyJJS awesome!

Want to give it a try a make a pull request 😏 ?
