### ISSUE TITLE
Update `{correlation}` on CRAN to prevents user from seeing deprecation warnings

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#319]
``` r
options(warn = 2L)
library(correlation)

correlation(anscombe) |> standardize_names()
#> Error: (converted from warning) Function `data_find()` is deprecated and will be removed in a future
#>   release. Please use `extract_column_names()` instead.
```

<sup>Created on 2024-06-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

This is already fixed in the devel version:

https://github.com/easystats/correlation/blob/19e052ba4a82f88cd70660905f8dbd8612d5b5a0/R/methods.easycorrelation.R#L123

**Comment by strengejacke** [comment]
Why is this not recognized in CRAN checks? I thought after updating _datawizard_, several packages (performance, parameters, correlation, ...) would "break" due to deprecation warnings?

**Comment by IndrajeetPatil** [comment]
CRAN doesn't run its checks with "warnings as errors" setting.

**Comment by etiennebacher** [comment]
I got a message about failed revdep but only for easystats, performance and modelbased:

> ** Changes to worse in reverse dependencies ***
Debian: <https://win-builder.r-project.org/incoming_pretest/datawizard_0.11.0_20240604_155901/reverseDependencies/summary.txt>
easystats, modelbased, performance

The binaries of datawizard for windows were built last night only, are you sure that you got those warnings with datawizard 0.11.0?

**Comment by IndrajeetPatil** [comment]
I discovered this because the CI in my personal projects does use this setting.

**Comment by strengejacke** [comment]
> I got a message about failed revdep but only for easystats, performance and modelbased:
> 
> > ** Changes to worse in reverse dependencies ***
> > Debian: https://win-builder.r-project.org/incoming_pretest/datawizard_0.11.0_20240604_155901/reverseDependencies/summary.txt
> > easystats, modelbased, performance
> 
> The binaries of datawizard for windows were built last night only, are you sure that you got those warnings with datawizard 0.11.0?

And the errors in _performance_ and _easystats_ were unrelated to the deprecation changes in _datawizard_, so you effectively got only an expected warning for _modelbased_.

Either way, all affected packages are prepared for submission to CRAN (except maybe _see_, which I haven't checked yet).
