### ISSUE TITLE
using correlation in shiny apps in shinyapps.io

### ISSUE THREAD

**Issue by sbalci** [easystats/correlation#32]
Hello,
Thank you for the package.

Your package is working as expected in local shiny apps. But when I try to upload it to a _shinyapps.io_ server, I get the following error: 

`installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores Execution halted`

I think there is a missing metadata in the package as described in this post:  
https://community.rstudio.com/t/error-when-using-devtools-install-github-with-shiny-for-private-repository/39053/2?u=serdarbalci

Best wishes

**Comment by DominiqueMakowski** [comment]
Dear @sbalci, I would assume that the error is caused by the fact that the correlation package is not yet on CRAN 😕 we plan to submit it soon (very beginning of January). I'll keep you updated! Apologies for the inconvenience

**Comment by sbalci** [comment]
Thank you very much for the information and the package :)
