### ISSUE TITLE
Fix CRAN note

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#323]
cf. https://cran.r-project.org/web/checks/check_results_correlation.html

```r
Version: 0.8.5
Check: Rd cross-references
Result: NOTE 
  Found the following Rd file(s) with Rd \link{} targets missing package
  anchors:
    cor_test.Rd: parameters, winsorize
    correlation.Rd: parameters, winsorize
  Please provide package anchors for all Rd \link{} targets not in the
  package itself and the base packages.
```

**Comment by strengejacke** [comment]
Should we also fix the two errors and change the _datawizard_ version to 0.10.0?

**Comment by IndrajeetPatil** [comment]
> Should we also fix the two errors and change the _datawizard_ version to 0.10.0?

I'd say yes. We should also review and merge the pending PRs in this repo (the ones which are relevant) .
