### ISSUE TITLE
Partial / Rank correlation documentation

### ISSUE THREAD

**Issue by mattansb** [easystats/correlation#45]
I think it should be made more explicit (especially for the Bayesian methods) how Partial and Rank correlation are actually obtained. 

- These are not "true" Bayesian rank correlations (which have some [weird priors](https://doi.org/10.1080/02664763.2019.1709053) that I don't understand), but x & y a rank transformed and then these are tested for a Pearson correlation.
- And these are not "true" Bayesian partial correlations (no prior for the correlation between `X<->Z` or `Z<->Y`), but `Z` is partial-ed out of x & y using OLS, and then these residual-scores are tested for a Pearson correlation.

**Comment by DominiqueMakowski** [comment]
yes! that package definitely needs a proper documentation and articles...

Regarding these two points, should we call them "pseudo-Bayesian" correlations?

**Comment by mattansb** [comment]
Hmm.. The correlation is Bayesian, it's the "method" isn't.. Maybe "Bayesian pseudo-Spearman / pseudo-partial correlation (see details)"?

**Comment by DominiqueMakowski** [comment]
haha good point
