### ISSUE TITLE
CRAN initial submission

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#6]
@strengejacke I think I might try adding a bit more tests, and then go ahead with submission. Although there are potential developments for this package (#2), I think it should be ok for an initial release. What do you think?

**Comment by DominiqueMakowski** [comment]
Oh no but it depends on parameters and bayestestR! haha ok let's focus on these two first

**Comment by IndrajeetPatil** [comment]
Now that both `parameters` and `bayestestR` are on `CRAN`, maybe this can be submitted to `CRAN` as well?

**Comment by DominiqueMakowski** [comment]
Yup, I don't see why not. I think the code might benefit from some cleaning/improvement (it has been written at the beginning of easystats), I will look into it soon. Do you need it at CRAN for a particular deadline?

**Comment by IndrajeetPatil** [comment]
No, no, no deadline. Was just curious about the timeline.

**Comment by strengejacke** [comment]
We should remove the dplyr-dependency...

**Comment by DominiqueMakowski** [comment]
This one is IMO good to go as soon as effectsize 0.1.2 is on CRAN.

Quite happy about it it's quite powerful, although it definitely lacks proper documentation 😢

**Comment by IndrajeetPatil** [comment]
This looks super-awesome! I am excited about this making it to CRAN soon. I plan to rely on it for `ggstatsplot`. The syntax interface and the functionality are way better than any of the existing packages that deal with correlations.

**Comment by houyunhuang** [comment]
I'm excited about the release of the correlation package, and I plan to rely on correlation in ggcor (still under development).

**Comment by DominiqueMakowski** [comment]
It has been submitted yesterday, so it should be sooner than later ☺️  

btw @houyunhuang ggcor looks terrific!

**Comment by houyunhuang** [comment]
`ggcor` is not stable yet and I expect it to be better next month.@DominiqueMakowski

**Comment by DominiqueMakowski** [comment]
On its way to CRAN :tada:
