### ISSUE TITLE
`NEWS` needs to catch up with the CRAN version

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/correlation#65]
I see `correlation 0.2.0` on `CRAN`, but this is not reflected in the `NEWS` documentation:
https://cran.r-project.org/web/packages/correlation/news/news.html

![image](https://user-images.githubusercontent.com/11330453/78883237-83cab780-7a59-11ea-916c-7e6753a5f463.png)

**Comment by DominiqueMakowski** [comment]
@strengejacke 😂

**Comment by DominiqueMakowski** [comment]
I'm sorry I'm terrible at maintaining news files 🤷‍♂️ 

![](https://media.giphy.com/media/cz314BBYiCkiA/giphy.gif)

**Comment by strengejacke** [comment]
And since he *never* merges current master into dev, but *persists* on working with dev, all the relevant features will never make it to CRAN...

![giphy](https://user-images.githubusercontent.com/26301769/78884254-ec666400-7a5a-11ea-999f-3e8820645155.gif)

**Comment by DominiqueMakowski** [comment]
Playing with branches

![](https://media.giphy.com/media/OBMIU5KPtA56E/giphy.gif)

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
https://blog.r-hub.io/2020/05/08/pkg-news/

**Comment by strengejacke** [comment]
<sup>(I think @DominiqueMakowski unsubscribed from this issue...)</sup> 😄

**Comment by DominiqueMakowski** [comment]
haha no but it's up to date as of last push: https://github.com/easystats/correlation/blob/master/NEWS.md

**Comment by strengejacke** [comment]
_bump_
