### ISSUE TITLE
We need equations

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#67]
as JOSS reopens soon @mattansb @strengejacke @IndrajeetPatil the kings of equations, Gondor calls for aid!

![](https://media.giphy.com/media/BmmfETghGOPrW/giphy.gif)

Would be cool to add a few equations (you know, because science and all) when possible below the description of the different correlation types (in the [paper](https://github.com/easystats/correlation/blob/master/paper/paper.md#introduction) and the [docstrings](https://github.com/easystats/correlation/blob/master/R/correlation.R#L14)) 😼

**Comment by strengejacke** [comment]
isn't it just `y ~ x`?

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/sDOhzJBsFvjMY/giphy.gif)

**Comment by mattansb** [comment]
Added Pearson, Spearman and Partial... Don't really know the other ones...

**Comment by DominiqueMakowski** [comment]
We can prolly skip this one (from https://github.com/easystats/correlation/issues/13) 😁 
 
![image](https://user-images.githubusercontent.com/8875533/79042274-c8587d80-7c28-11ea-8c51-1690ef00c720.png)
