### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#69]
"JOSS submissions are suspended until at least 4th May 2020" 😞 

Another alternative could be [JORS](https://openresearchsoftware.metajnl.com/) (never tried), which has publication fees (£400.00) *but* says `If you do not have funds to pay such fees, you will have an opportunity to waive each fee. We do not want fees to prevent the publication of worthy work.` (bottom of [here](https://openresearchsoftware.metajnl.com/about/submissions/)). Which could apply here, as easystats (as the mother-project) has no funding. What do you say?

@strengejacke @mattansb @IndrajeetPatil

**Comment by DominiqueMakowski** [comment]
*bump*

**Comment by IndrajeetPatil** [comment]
I think _JORS_ seems like a good option! I went through some of their published articles and this paper will fit there.

Another option is _Collabra_, but I think that will be too psychology focused when the package is useful across multiple disciplines and expects a wider readership. 

![image](https://user-images.githubusercontent.com/11330453/79548097-32dc4400-8095-11ea-8a83-2cd26bfe1f91.png)

But I still feel like it might be worth waiting until the first week of May for _JOSS_ to reopen. That will be the most natural home for this paper.

**Comment by strengejacke** [comment]
I'm not sure we're applicable for waiving the fees, but anyway: It seems that the effort for submissions is quite high, especially regarding the "impact" of this journal.

**Comment by DominiqueMakowski** [comment]
Alright then, let's wait for joss

**Comment by DominiqueMakowski** [comment]
So JOSS has reopened, do we have any blockers for proceeding?

**Comment by mattansb** [comment]
Only internal blockers 😅

**Comment by DominiqueMakowski** [comment]
> Only internal blockers 

How so?

**Comment by mattansb** [comment]
Internal blockers = psychological factors 😜

**Comment by DominiqueMakowski** [comment]
I'd say we can submit and then we'll see, because I don't see what else we can improve/add in the near future that'd be a must-have for submission.

The only thing would be CI (I mean continuous integration), that should be working prior to submission. I'll see what I can do

**Comment by DominiqueMakowski** [comment]
travis passes so I guess we could submit... @strengejacke thoughts?

**Comment by strengejacke** [comment]
No, I stopped thinking some weeks ago...

**Comment by DominiqueMakowski** [comment]
I sense some strong inertia here 🙄 but I assume you don't have anything *against* submission (if so let them speak now or forever hold their peace 💍)

**Comment by DominiqueMakowski** [comment]
https://joss.theoj.org/papers/40579b4c55e01a7119c54cf70bbe3d74

**Comment by strengejacke** [comment]
No, nothing against submission of course.
The link doesn't work.

**Comment by DominiqueMakowski** [comment]
Maybe 'cause it's private. it just says that it's submitted ☺️

**Comment by DominiqueMakowski** [comment]
https://github.com/openjournals/joss-reviews/issues/2233#issuecomment-633037812

**Comment by DominiqueMakowski** [comment]
https://github.com/openjournals/joss-papers/blob/joss.02233/joss.02233/10.21105.joss.02233.pdf 

How can we address the fact that the output from some of the tables is too wide?

**Comment by mattansb** [comment]
Would shortening the variable/group names help?
Or we can host an html version of the paper and link to it...

**Comment by DominiqueMakowski** [comment]
https://github.com/openjournals/joss-papers/blob/joss.02233/joss.02233/10.21105.joss.02233.pdf

latex commands for size seem to work (see first code output), altho `tiny` might be a bit too small ^^
