### ISSUE TITLE
Error in multi-level correlation when using Spearman's Rho: "undefined columns selected"

### ISSUE THREAD

**Issue by HaraldBrolin** [easystats/correlation#75]
I noticed this error when I was trying to perform a multi-level Spearman's correlation, I did not run into the same problem when using Pearson's correlation. Maybe it's not possible to run a multi-level Spearman's correlation due to the data being ranked?

Also I used an older version of R, 3.6.1. 

```
library(correlation)
library(ggplot2)

data <- simulate_simpson(n=100, groups=10)
correlation(data, multilevel = TRUE, method = "spearman")
```

> Error in `[.data.frame`(cor, , 1:ncol(newdata)) : 
  undefined columns selected

R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

**Comment by DominiqueMakowski** [comment]
@HaraldBrolin apologies for the delay, but it should be fixed now on the dev branch ☺️
