### ISSUE TITLE
CRAN issues

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/correlation#76]
```
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_correlation.html>.

Please correct before 2020-05-16 to safely retain your package on CRAN.
```

**Comment by strengejacke** [comment]
Any idea why the results changed?

**Comment by DominiqueMakowski** [comment]
no idea, especially since it's inconsistent. Could be due to the `psych` package

**Comment by strengejacke** [comment]
Local checks pass, fixed on test-issue (and removed dplyr-dep in code), now waiting for Travis.

**Comment by strengejacke** [comment]
We should send to win-builder as well, it sometimes detects issues not found by local checks.

**Comment by strengejacke** [comment]
This line fails in the tests:

```r
if (all.equal(out$rho, 0.7507764, tol = 0.01)) {
```

Not sure, why? Seems that on Mac, `all.equal()` does not return `TRUE`, see from `?all.equal`:

> Either TRUE (NULL for attr.all.equal) or a vector of mode "character" describing the differences between target and current.

Trying to wrap in `isTRUE()`.

**Comment by DominiqueMakowski** [comment]
uploaded to winbuilder

**Comment by DominiqueMakowski** [comment]
thanks, package correlation_0.2.1.tar.gz is on its way to CRAN.

**Comment by strengejacke** [comment]
Hm, [too late](https://github.com/easystats/correlation/issues/65) ;-)
