### ISSUE TITLE
Typos in paper

### ISSUE THREAD

**Issue by mmrabe** [easystats/correlation#93]
As part of the JOSS paper review, here are some minor suggestions for the paper:

- [x] p. 1: *than* doesn't feel like the right preposition here, maybe **to** or **over**?
- [x] p. 1: write out % as “percentage” or “proportion”
- [x] p. 1: in formula, what do *i* and *j* refer to?
- [x] p. 2: one or more variable**s**
- [x] p. 3: include**s**
- [x] p. 5: replace exclamation mark with period
- [x] p. 6: in**t**ercepts

**Comment by DominiqueMakowski** [comment]
Thanks @mmrabe for your comments. We have addressed all of them.
