### ISSUE TITLE
Vignettes inaccessible?

### ISSUE THREAD

**Issue by mmrabe** [easystats/correlation#95]
I was unable to access the package vignettes from the CRAN repository package page or the vignette(package="correlations") function. Are they properly linked? Also, in the README when using devtools::install_github, I would suggest adding build_vignettes=TRUE for similar reasons.

**Comment by strengejacke** [comment]
Package vignettes are only available via the dedicated website, they're not shipped with the package. I'm not sure, but maybe that was too much overload? @DominiqueMakowski ?

**Comment by DominiqueMakowski** [comment]
Mmh good question, I don't remember having done anything voluntarily that could have affected this issue. Maybe we overlooked something in the settings or the YAML header, will give it a look!

**Comment by strengejacke** [comment]
rbuildignore does not ship vignettes: https://github.com/easystats/correlation/blob/master/.Rbuildignore

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by strengejacke** [comment]
Dunno... Ask this guy:

![image](https://user-images.githubusercontent.com/26301769/86138313-98659b80-baee-11ea-8ff1-241a35fbf060.png)

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/l3fZFvp94ljepXoPe/giphy.gif)

**Comment by DominiqueMakowski** [comment]
Thanks a lot @mmrabe for pointing that issue to us, it should be fixed now in the next CRAN release.
