### ISSUE TITLE
add directional hypothesis testing to cor_test

### ISSUE THREAD

**Issue by baranovskypd** [easystats/correlation#99]
Could you please add the ability to perform directional hypothesis testing with cor_test(), similar to stats::cor.test() where one can specify the 'alternative' argument that takes values "two.sided", "greater" or "less"? E.g.: alternative = "greater"

**Comment by DominiqueMakowski** [comment]
@baranovskypd apologies I missed your post. Yes, we could potentially support that, I'll see what I can do.

**Comment by DominiqueMakowski** [comment]
I allowed for the argument to pass through... it should work with the latest github version. Let me know if there's anything else!

![image](https://user-images.githubusercontent.com/8875533/93324507-976c1c80-f848-11ea-9c86-c89f48f1b176.png)

**Comment by baranovskypd** [comment]
Thank you, it works fine!
